// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class AssetName
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public string Name { get; set; } = null!;

    public Guid? CategoryId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<AssetType> AssetTypes { get; set; } = new List<AssetType>();

    public virtual AssetCategory? Category { get; set; }

    public virtual Club Club { get; set; } = null!;
}