namespace SportStock.Api.Data.Entities;

// Keyless result row for the PostgreSQL function get_asset_depreciation(batch_id).
// Hand-written: function result types are not generated by EF Core Power Tools.
// Registered as keyless entity in SportStockDbContext.OnModelCreatingPartial.
public sealed class AssetDepreciationRow
{
    public Guid BatchId { get; set; }
    public Guid AssetTypeId { get; set; }
    public decimal PurchasePrice { get; set; }
    public decimal AnnualDepreciation { get; set; }
    public decimal YearsElapsed { get; set; }
    public decimal AccumulatedDepreciation { get; set; }
    public decimal NetBookValue { get; set; }
}
