// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class Club
{
    public Guid Id { get; set; }
    public string Name { get; set; } = null!;
    public Guid? SportTypeId { get; set; }
    public string? Address { get; set; }
    public string? ContactEmail { get; set; }
    public string? LogoUrl { get; set; }
    public Guid? OwnerId { get; set; }
    public int LowStockThreshold { get; set; }
    public string RetirementAlertMode { get; set; } = null!;
    public int RetirementAlertValue { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    public virtual SportType? SportType { get; set; }
    public virtual User? Owner { get; set; }
    public virtual ICollection<ClubMembership> Memberships { get; set; } = new List<ClubMembership>();
    public virtual ICollection<Warehouse> Warehouses { get; set; } = new List<Warehouse>();
}