// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class Loan
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public Guid CoachId { get; set; }

    public Guid? TeamId { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? ApprovedBy { get; set; }

    public Guid? CheckoutBy { get; set; }

    public Guid? ReturnConfirmedBy { get; set; }

    public Guid? WarehouseId { get; set; }

    public string? Reason { get; set; }

    public DateOnly DueDate { get; set; }

    public string? RejectionReason { get; set; }

    public DateTime? CheckedOutAt { get; set; }

    public DateTime? ReturnedAt { get; set; }

    public string? ReturnNotes { get; set; }

    public DateTime? DueReminderSentAt { get; set; }

    public DateTime? OverdueNotifiedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Warehouse? Warehouse { get; set; }

    public virtual User? ApprovedByNavigation { get; set; }

    public virtual User? CheckoutByNavigation { get; set; }

    public virtual Club Club { get; set; } = null!;

    public virtual User Coach { get; set; } = null!;

    public virtual User? CreatedByNavigation { get; set; }

    public virtual ICollection<LoanItem> LoanItems { get; set; } = new List<LoanItem>();

    public virtual User? ReturnConfirmedByNavigation { get; set; }

    public virtual ICollection<StockMovement> StockMovements { get; set; } = new List<StockMovement>();

    public virtual Team? Team { get; set; }
}