// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class Notification
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public Guid UserId { get; set; }

    public string Title { get; set; } = null!;

    public string? Body { get; set; }

    public string? Data { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Club Club { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}