// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class StockMovement
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public Guid? AssetBatchId { get; set; }

    public Guid? LoanId { get; set; }

    public Guid? LoanItemId { get; set; }

    public Guid? OperatorId { get; set; }

    public int QuantityDelta { get; set; }

    public int QuantityBefore { get; set; }

    public int QuantityAfter { get; set; }

    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AssetBatch? AssetBatch { get; set; }

    public virtual Club Club { get; set; } = null!;

    public virtual Loan? Loan { get; set; }

    public virtual LoanItem? LoanItem { get; set; }

    public virtual User? Operator { get; set; }
}