// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class StocktakeSession
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public Guid ConductedBy { get; set; }

    public string Status { get; set; } = null!;

    public string? Notes { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Club Club { get; set; } = null!;

    public virtual User ConductedByNavigation { get; set; } = null!;

    public virtual ICollection<StocktakeItem> StocktakeItems { get; set; } = new List<StocktakeItem>();
}