// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class User
{
    public Guid Id { get; set; }
    public string Email { get; set; } = null!;
    public string PasswordHash { get; set; } = null!;
    public string FirstName { get; set; } = null!;
    public string LastName { get; set; } = null!;
    public string? Phone { get; set; }
    public string? AvatarUrl { get; set; }
    public bool IsSupAdmin { get; set; }
    public bool EmailVerified { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ClubMembership> ClubMemberships { get; set; } = new List<ClubMembership>();
    public virtual ICollection<ClubInvitation> SentInvitations { get; set; } = new List<ClubInvitation>();
    public virtual ICollection<ClubInvitation> ReceivedInvitations { get; set; } = new List<ClubInvitation>();
}