// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class WriteOffOrder
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public Guid AssetTypeId { get; set; }

    public int Quantity { get; set; }

    public string? Reason { get; set; }

    public Guid? LoanItemId { get; set; }

    public Guid CreatedBy { get; set; }

    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual AssetType AssetType { get; set; } = null!;

    public virtual Club Club { get; set; } = null!;

    public virtual User CreatedByNavigation { get; set; } = null!;

    public virtual LoanItem? LoanItem { get; set; }
}