// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class AssetType
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public Guid AssetNameId { get; set; }

    public string? Brand { get; set; }

    public string? Model { get; set; }

    public string? Size { get; set; }

    public string? ImageUrl { get; set; }

    public int? LowStockThreshold { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AssetBatch> AssetBatches { get; set; } = new List<AssetBatch>();

    public virtual AssetName AssetName { get; set; } = null!;

    public virtual Club Club { get; set; } = null!;

    public virtual ICollection<LoanItem> LoanItems { get; set; } = new List<LoanItem>();

    public virtual ICollection<StocktakeItem> StocktakeItems { get; set; } = new List<StocktakeItem>();

    public virtual ICollection<WriteOffOrder> WriteOffOrders { get; set; } = new List<WriteOffOrder>();
}