// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class AssetCategory
{
    public Guid Id { get; set; }

    public Guid? ClubId { get; set; }

    public string Name { get; set; } = null!;

    public bool IsSystem { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<AssetName> AssetNames { get; set; } = new List<AssetName>();

    public virtual Club? Club { get; set; }
}