// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class LoanItem
{
    public Guid Id { get; set; }

    public Guid LoanId { get; set; }

    public Guid AssetTypeId { get; set; }

    public int Quantity { get; set; }

    public int? GoodQuantity { get; set; }

    public int? MinorDamageQuantity { get; set; }

    public int? WriteOffQuantity { get; set; }

    public int? LostQuantity { get; set; }

    public string? ReturnNotes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual AssetType AssetType { get; set; } = null!;

    public virtual Loan Loan { get; set; } = null!;

    public virtual ICollection<StockMovement> StockMovements { get; set; } = new List<StockMovement>();

    public virtual ICollection<WriteOffOrder> WriteOffOrders { get; set; } = new List<WriteOffOrder>();
}