// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class StocktakeItem
{
    public Guid Id { get; set; }

    public Guid SessionId { get; set; }

    public Guid AssetTypeId { get; set; }

    public int SystemQuantity { get; set; }

    public int PhysicalQuantity { get; set; }

    public int? Variance { get; set; }

    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AssetType AssetType { get; set; } = null!;

    public virtual StocktakeSession Session { get; set; } = null!;
}