// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SportStock.Api.Data.Entities;

public partial class Team
{
    public Guid Id { get; set; }

    public Guid ClubId { get; set; }

    public string Name { get; set; } = null!;

    public string Gender { get; set; } = null!;

    public string AgeGroup { get; set; } = null!;

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Club Club { get; set; } = null!;

    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();

    public virtual TeamMember? TeamMember { get; set; }
}