// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SportStock.Api.Data.Entities;

namespace SportStock.Api.Data;

public partial class SportStockDbContext : DbContext
{
    public SportStockDbContext(DbContextOptions<SportStockDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AssetBatch> AssetBatches { get; set; }

    public virtual DbSet<AssetCategory> AssetCategories { get; set; }

    public virtual DbSet<AssetItem> AssetItems { get; set; }

    public virtual DbSet<AssetName> AssetNames { get; set; }

    public virtual DbSet<AssetType> AssetTypes { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Club> Clubs { get; set; }

    public virtual DbSet<ClubInvitation> ClubInvitations { get; set; }

    public virtual DbSet<ClubMembership> ClubMemberships { get; set; }

    public virtual DbSet<EmailVerification> EmailVerifications { get; set; }

    public virtual DbSet<FcmToken> FcmTokens { get; set; }

    public virtual DbSet<Kit> Kits { get; set; }

    public virtual DbSet<KitItem> KitItems { get; set; }

    public virtual DbSet<Loan> Loans { get; set; }

    public virtual DbSet<LoanItem> LoanItems { get; set; }

    public virtual DbSet<LoanItemAssignment> LoanItemAssignments { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<SportType> SportTypes { get; set; }

    public virtual DbSet<StockMovement> StockMovements { get; set; }

    public virtual DbSet<StocktakeItem> StocktakeItems { get; set; }

    public virtual DbSet<StocktakeSession> StocktakeSessions { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamMember> TeamMembers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Warehouse> Warehouses { get; set; }

    public virtual DbSet<WriteOffOrder> WriteOffOrders { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("asset_status", new[] { "available", "on_loan", "maintenance", "retired" })
            .HasPostgresEnum("loan_status", new[] { "pending", "approved", "rejected", "checked_out", "returned" })
            .HasPostgresEnum("notification_type", new[] { "loan_request", "loan_approved", "loan_rejected", "loan_due_reminder", "loan_overdue", "low_stock", "return_initiated" })
            .HasPostgresEnum("stock_movement_type", new[] { "purchase", "loan_out", "loan_return", "write_off", "adjustment" })
            .HasPostgresEnum("user_role", new[] { "super_admin", "club_admin", "asset_manager", "coach" })
            .HasPostgresEnum("write_off_source", new[] { "manual", "loan_return", "loan_lost" });

        modelBuilder.Entity<AssetBatch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("asset_batches_pkey");

            entity.ToTable("asset_batches");

            entity.HasIndex(e => new { e.AssetTypeId, e.PurchaseDate, e.CreatedAt }, "idx_asset_batches_checkout").HasFilter("((available_quantity > 0) AND (status <> 'retired'::asset_status))");

            entity.HasIndex(e => e.AssetTypeId, "idx_asset_batches_type_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AssetTypeId).HasColumnName("asset_type_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.PurchaseDate).HasColumnName("purchase_date");
            entity.Property(e => e.PurchasePrice)
                .HasPrecision(12, 2)
                .HasColumnName("purchase_price");
            entity.Property(e => e.TotalQuantity).HasColumnName("total_quantity");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UsefulLifeYears).HasColumnName("useful_life_years");

            entity.HasOne(d => d.AssetType).WithMany(p => p.AssetBatches)
                .HasForeignKey(d => d.AssetTypeId)
                .HasConstraintName("asset_batches_asset_type_id_fkey");
        });

        modelBuilder.Entity<AssetCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("asset_categories_pkey");

            entity.ToTable("asset_categories");

            entity.HasIndex(e => new { e.ClubId, e.Name }, "uq_asset_categories_club_name")
                .IsUnique()
                .HasFilter("(club_id IS NOT NULL)");

            entity.HasIndex(e => e.Name, "uq_asset_categories_system_name")
                .IsUnique()
                .HasFilter("(club_id IS NULL)");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.IsSystem).HasColumnName("is_system");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");

            entity.HasOne(d => d.Club).WithMany()
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("asset_categories_club_id_fkey");
        });

        modelBuilder.Entity<AssetName>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("asset_names_pkey");

            entity.ToTable("asset_names");

            entity.HasIndex(e => new { e.ClubId, e.Name }, "asset_names_club_id_name_key").IsUnique();

            entity.HasIndex(e => new { e.ClubId, e.CategoryId }, "idx_asset_names_club_category");

            entity.HasIndex(e => e.ClubId, "idx_asset_names_club_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");

            entity.HasOne(d => d.Category).WithMany(p => p.AssetNames)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("asset_names_category_id_fkey");

            entity.HasOne(d => d.Club).WithMany()
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("asset_names_club_id_fkey");
        });

        modelBuilder.Entity<AssetType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("asset_types_pkey");

            entity.ToTable("asset_types");

            entity.HasIndex(e => e.AssetNameId, "idx_asset_types_asset_name_id");

            entity.HasIndex(e => e.ClubId, "idx_asset_types_club_active").HasFilter("(is_active = true)");

            entity.HasIndex(e => e.ClubId, "idx_asset_types_club_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AssetNameId).HasColumnName("asset_name_id");
            entity.Property(e => e.Brand)
                .HasMaxLength(100)
                .HasColumnName("brand");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.ImageUrl).HasColumnName("image_url");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.LowStockThreshold).HasColumnName("low_stock_threshold");
            entity.Property(e => e.Model)
                .HasMaxLength(100)
                .HasColumnName("model");
            entity.Property(e => e.Size)
                .HasMaxLength(100)
                .HasColumnName("size");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.AssetName).WithMany(p => p.AssetTypes)
                .HasForeignKey(d => d.AssetNameId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("asset_types_asset_name_id_fkey");

            entity.HasOne(d => d.Club).WithMany()
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("asset_types_club_id_fkey");
        });

        modelBuilder.Entity<Club>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("clubs_pkey");

            entity.ToTable("clubs");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Address).HasColumnName("address");
            entity.Property(e => e.ContactEmail)
                .HasMaxLength(255)
                .HasColumnName("contact_email");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.LogoUrl).HasColumnName("logo_url");
            entity.Property(e => e.LowStockThreshold)
                .HasDefaultValue(2)
                .HasColumnName("low_stock_threshold");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.RetirementAlertMode)
                .HasMaxLength(10)
                .HasDefaultValueSql("'percent'::character varying")
                .HasColumnName("retirement_alert_mode");
            entity.Property(e => e.RetirementAlertValue)
                .HasDefaultValue(80)
                .HasColumnName("retirement_alert_value");
            entity.Property(e => e.SportTypeId)
                .HasColumnName("sport_type_id");
            entity.Property(e => e.OwnerId)
                .HasColumnName("owner_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.SportType).WithMany()
                .HasForeignKey(d => d.SportTypeId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("clubs_sport_type_id_fkey");

            entity.HasOne(d => d.Owner).WithMany()
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("clubs_owner_id_fkey");
        });

        modelBuilder.Entity<EmailVerification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("email_verifications_pkey");

            entity.ToTable("email_verifications");

            entity.HasIndex(e => new { e.Email, e.Type }, "idx_email_verifications_lookup").HasFilter("(used_at IS NULL)");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Code)
                .HasMaxLength(6)
                .HasColumnName("code");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.ExpiresAt)
                .HasDefaultValueSql("(now() + '00:15:00'::interval)")
                .HasColumnName("expires_at");
            entity.Property(e => e.Type)
                .HasMaxLength(20)
                .HasColumnName("type");
            entity.Property(e => e.UsedAt).HasColumnName("used_at");
        });

        modelBuilder.Entity<FcmToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("fcm_tokens_pkey");

            entity.ToTable("fcm_tokens");

            entity.HasIndex(e => new { e.UserId, e.Token }, "fcm_tokens_user_id_token_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DeviceInfo)
                .HasColumnType("jsonb")
                .HasColumnName("device_info");
            entity.Property(e => e.Token).HasColumnName("token");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fcm_tokens_user_id_fkey");
        });

        modelBuilder.Entity<Loan>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("loans_pkey");

            entity.ToTable("loans");

            entity.HasIndex(e => e.DueDate, "idx_loans_active_due").HasFilter("(status = 'checked_out'::loan_status)");

            entity.HasIndex(e => e.ClubId, "idx_loans_club_id");

            entity.HasIndex(e => e.CoachId, "idx_loans_coach_id");

            entity.HasIndex(e => e.TeamId, "idx_loans_team_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.ApprovedBy).HasColumnName("approved_by");
            entity.Property(e => e.CheckedOutAt).HasColumnName("checked_out_at");
            entity.Property(e => e.CheckoutBy).HasColumnName("checkout_by");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CoachId).HasColumnName("coach_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DueDate).HasColumnName("due_date");
            entity.Property(e => e.DueReminderSentAt).HasColumnName("due_reminder_sent_at");
            entity.Property(e => e.OverdueNotifiedAt).HasColumnName("overdue_notified_at");
            entity.Property(e => e.Reason).HasColumnName("reason");
            entity.Property(e => e.RejectionReason).HasColumnName("rejection_reason");
            entity.Property(e => e.ReturnConfirmedBy).HasColumnName("return_confirmed_by");
            entity.Property(e => e.ReturnNotes).HasColumnName("return_notes");
            entity.Property(e => e.ReturnedAt).HasColumnName("returned_at");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.ApprovedByNavigation).WithMany()
                .HasForeignKey(d => d.ApprovedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("loans_approved_by_fkey");

            entity.HasOne(d => d.CheckoutByNavigation).WithMany()
                .HasForeignKey(d => d.CheckoutBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("loans_checkout_by_fkey");

            entity.HasOne(d => d.Club).WithMany()
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("loans_club_id_fkey");

            entity.HasOne(d => d.Coach).WithMany()
                .HasForeignKey(d => d.CoachId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("loans_coach_id_fkey");

            entity.HasOne(d => d.CreatedByNavigation).WithMany()
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("loans_created_by_fkey");

            entity.HasOne(d => d.ReturnConfirmedByNavigation).WithMany()
                .HasForeignKey(d => d.ReturnConfirmedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("loans_return_confirmed_by_fkey");

            entity.HasOne(d => d.Team).WithMany(p => p.Loans)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("loans_team_id_fkey");
        });

        modelBuilder.Entity<LoanItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("loan_items_pkey");

            entity.ToTable("loan_items");

            entity.HasIndex(e => e.AssetTypeId, "idx_loan_items_asset_type_id");

            entity.HasIndex(e => e.LoanId, "idx_loan_items_loan_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AssetTypeId).HasColumnName("asset_type_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.GoodQuantity).HasColumnName("good_quantity");
            entity.Property(e => e.LoanId).HasColumnName("loan_id");
            entity.Property(e => e.LostQuantity).HasColumnName("lost_quantity");
            entity.Property(e => e.MinorDamageQuantity).HasColumnName("minor_damage_quantity");
            entity.Property(e => e.Quantity)
                .HasDefaultValue(1)
                .HasColumnName("quantity");
            entity.Property(e => e.KitId).HasColumnName("kit_id");
            entity.Property(e => e.KitName).HasColumnName("kit_name").HasMaxLength(100);
            entity.Property(e => e.KitQuantity).HasColumnName("kit_quantity");
            entity.Property(e => e.ReturnNotes).HasColumnName("return_notes");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.WriteOffQuantity).HasColumnName("write_off_quantity");

            entity.HasOne(d => d.Kit)
                .WithMany()
                .HasForeignKey(d => d.KitId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("loan_items_kit_id_fkey");

            entity.HasOne(d => d.AssetType).WithMany(p => p.LoanItems)
                .HasForeignKey(d => d.AssetTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("loan_items_asset_type_id_fkey");

            entity.HasOne(d => d.Loan).WithMany(p => p.LoanItems)
                .HasForeignKey(d => d.LoanId)
                .HasConstraintName("loan_items_loan_id_fkey");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("notifications_pkey");

            entity.ToTable("notifications");

            entity.HasIndex(e => e.UserId, "idx_notifications_unread").HasFilter("(is_read = false)");

            entity.HasIndex(e => new { e.UserId, e.CreatedAt }, "idx_notifications_user_ts").IsDescending(false, true);

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Body).HasColumnName("body");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Data)
                .HasColumnType("jsonb")
                .HasColumnName("data");
            entity.Property(e => e.IsRead).HasColumnName("is_read");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Club).WithMany()
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("notifications_club_id_fkey");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("notifications_user_id_fkey");
        });

        modelBuilder.Entity<StockMovement>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("stock_movements_pkey");

            entity.ToTable("stock_movements");

            entity.HasIndex(e => new { e.AssetBatchId, e.CreatedAt }, "idx_stock_movements_batch_ts").IsDescending(false, true);

            entity.HasIndex(e => e.ClubId, "idx_stock_movements_club_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AssetBatchId).HasColumnName("asset_batch_id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.LoanId).HasColumnName("loan_id");
            entity.Property(e => e.LoanItemId).HasColumnName("loan_item_id");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.OperatorId).HasColumnName("operator_id");
            entity.Property(e => e.QuantityAfter).HasColumnName("quantity_after");
            entity.Property(e => e.QuantityBefore).HasColumnName("quantity_before");
            entity.Property(e => e.QuantityDelta).HasColumnName("quantity_delta");

            entity.HasOne(d => d.AssetBatch).WithMany(p => p.StockMovements)
                .HasForeignKey(d => d.AssetBatchId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("stock_movements_asset_batch_id_fkey");

            entity.HasOne(d => d.Club).WithMany()
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("stock_movements_club_id_fkey");

            entity.HasOne(d => d.Loan).WithMany(p => p.StockMovements)
                .HasForeignKey(d => d.LoanId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("stock_movements_loan_id_fkey");

            entity.HasOne(d => d.LoanItem).WithMany(p => p.StockMovements)
                .HasForeignKey(d => d.LoanItemId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("stock_movements_loan_item_id_fkey");

            entity.HasOne(d => d.Operator).WithMany()
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("stock_movements_operator_id_fkey");
        });

        modelBuilder.Entity<StocktakeItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("stocktake_items_pkey");

            entity.ToTable("stocktake_items");

            entity.HasIndex(e => new { e.SessionId, e.AssetTypeId }, "stocktake_items_session_id_asset_type_id_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AssetTypeId).HasColumnName("asset_type_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.PhysicalQuantity).HasColumnName("physical_quantity");
            entity.Property(e => e.SessionId).HasColumnName("session_id");
            entity.Property(e => e.SystemQuantity).HasColumnName("system_quantity");
            entity.Property(e => e.Variance)
                .HasComputedColumnSql("(physical_quantity - system_quantity)", true)
                .HasColumnName("variance");

            entity.HasOne(d => d.AssetType).WithMany(p => p.StocktakeItems)
                .HasForeignKey(d => d.AssetTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("stocktake_items_asset_type_id_fkey");

            entity.HasOne(d => d.Session).WithMany(p => p.StocktakeItems)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("stocktake_items_session_id_fkey");
        });

        modelBuilder.Entity<StocktakeSession>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("stocktake_sessions_pkey");

            entity.ToTable("stocktake_sessions");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CompletedAt).HasColumnName("completed_at");
            entity.Property(e => e.ConductedBy).HasColumnName("conducted_by");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.StartedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("started_at");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValueSql("'in_progress'::character varying")
                .HasColumnName("status");

            entity.HasOne(d => d.Club).WithMany()
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("stocktake_sessions_club_id_fkey");

            entity.HasOne(d => d.ConductedByNavigation).WithMany()
                .HasForeignKey(d => d.ConductedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("stocktake_sessions_conducted_by_fkey");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("teams_pkey");

            entity.ToTable("teams");

            entity.HasIndex(e => e.ClubId, "idx_teams_club_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AgeGroup)
                .HasMaxLength(10)
                .HasColumnName("age_group");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .HasColumnName("gender");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Club).WithMany()
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("teams_club_id_fkey");
        });

        modelBuilder.Entity<TeamMember>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("team_members_pkey");

            entity.ToTable("team_members");

            entity.HasIndex(e => e.TeamId, "idx_team_members_team_id");

            entity.HasIndex(e => e.UserId, "idx_team_members_user_id");

            entity.HasIndex(e => new { e.TeamId, e.UserId }, "team_members_team_id_user_id_key").IsUnique();

            entity.HasIndex(e => e.TeamId, "uq_team_head_coach")
                .IsUnique()
                .HasFilter("((team_role)::text = 'head_coach'::text)");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.TeamRole)
                .HasMaxLength(20)
                .HasColumnName("team_role");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Team).WithOne(p => p.TeamMember)
                .HasForeignKey<TeamMember>(d => d.TeamId)
                .HasConstraintName("team_members_team_id_fkey");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("team_members_user_id_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("users_pkey");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "idx_users_email");

            entity.HasIndex(e => e.Email, "users_email_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.EmailVerified).HasColumnName("email_verified");
            entity.Property(e => e.FirstName)
                .HasMaxLength(100)
                .HasColumnName("first_name");
            entity.Property(e => e.LastName)
                .HasMaxLength(100)
                .HasColumnName("last_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.IsSupAdmin)
                .HasDefaultValue(false)
                .HasColumnName("is_sup_admin");
            entity.Property(e => e.PasswordHash).HasColumnName("password_hash");
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .HasColumnName("phone");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<WriteOffOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("write_off_orders_pkey");

            entity.ToTable("write_off_orders");

            entity.HasIndex(e => e.AssetTypeId, "idx_write_off_orders_asset_type_id");

            entity.HasIndex(e => e.ClubId, "idx_write_off_orders_club_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AssetTypeId).HasColumnName("asset_type_id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.LoanItemId).HasColumnName("loan_item_id");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Reason).HasColumnName("reason");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.AssetType).WithMany(p => p.WriteOffOrders)
                .HasForeignKey(d => d.AssetTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("write_off_orders_asset_type_id_fkey");

            entity.HasOne(d => d.Club).WithMany()
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("write_off_orders_club_id_fkey");

            entity.HasOne(d => d.CreatedByNavigation).WithMany()
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("write_off_orders_created_by_fkey");

            entity.HasOne(d => d.LoanItem).WithMany(p => p.WriteOffOrders)
                .HasForeignKey(d => d.LoanItemId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("write_off_orders_loan_item_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}