using Microsoft.EntityFrameworkCore;
using SportStock.Api.Data.Entities;

namespace SportStock.Api.Data;

// Thin C# wrappers for PostgreSQL stored procedures and functions defined in
// backend/db-init.sql. These methods are not generated by EF Core Power Tools
// (PG procedure / function scaffolding is unreliable for Npgsql) and must be
// maintained by hand whenever a procedure signature changes in db-init.sql.
//
// Interpolated string parameters on ExecuteSqlAsync / FromSql are
// auto-parameterized by EF Core — no SQL injection risk.
public static class StoredProcedures
{
    public static Task<int> ApproveLoanAsync(
        this SportStockDbContext db,
        Guid loanId,
        Guid approverId,
        CancellationToken ct = default) =>
        db.Database.ExecuteSqlAsync(
            $"CALL approve_loan({loanId}, {approverId})", ct);

    public static Task<int> RejectLoanAsync(
        this SportStockDbContext db,
        Guid loanId,
        Guid approverId,
        string? reason,
        CancellationToken ct = default) =>
        db.Database.ExecuteSqlAsync(
            $"CALL reject_loan({loanId}, {approverId}, {reason})", ct);

    public static Task<int> CheckoutLoanAsync(
        this SportStockDbContext db,
        Guid loanId,
        Guid operatorId,
        CancellationToken ct = default) =>
        db.Database.ExecuteSqlAsync(
            $"CALL checkout_loan({loanId}, {operatorId})", ct);

    public static Task<int> CompleteMaintenanceAsync(
        this SportStockDbContext db,
        Guid batchId,
        Guid operatorId,
        int quantityRestored,
        string? notes,
        CancellationToken ct = default) =>
        db.Database.ExecuteSqlAsync(
            $"CALL complete_maintenance({batchId}, {operatorId}, {quantityRestored}, {notes})", ct);

    public static Task<int> RetireBatchAsync(
        this SportStockDbContext db,
        Guid batchId,
        Guid operatorId,
        int quantity,
        string? notes,
        CancellationToken ct = default) =>
        db.Database.ExecuteSqlAsync(
            $"CALL retire_batch({batchId}, {operatorId}, {quantity}, {notes})", ct);

    public static Task<List<AssetDepreciationRow>> GetAssetDepreciationAsync(
        this SportStockDbContext db,
        Guid batchId,
        CancellationToken ct = default) =>
        db.Set<AssetDepreciationRow>()
          .FromSql($"SELECT * FROM get_asset_depreciation({batchId})")
          .AsNoTracking()
          .ToListAsync(ct);
}
